### ISSUE TITLE
[Feature Request] Gruppen-Objekte in Services optional nicht (zu Hosts, ...) auflösen

### ISSUE THREAD

**Issue by lankenau-dp** [orrence/Netspoc-Vue#60]
Hallo! Man nehme die unten folgende Service-Definition und lasse sie sich in Netspoc-Vue anzeigen. Die im User-Bereich verwendeten Gruppen enthalten im Beispiel ausschließlich Host-Objekte. Die Gruppen-Objekte lassen sich in Netspoc-Vue nicht einsehen, lediglich die "aufgelöste" Form, also mit zu Host-Objekten expandierten Gruppen. Ich wünsche mir eine Option zum Umschalten zwischen aufgelösten (-> Anzeige wie bisher; im Beispiel mit Host-Objekten aus allen Gruppen) und nicht-aufgelösten Gruppen; vergleichbar mit der Option "User expandieren" für den User.
```
service:DEMO = {

 user = group:SERVERS-ZONE1,
        group:SERVERS-ZONE2,
        group:SERVERS-ZONE3,
        host:single-server-1_10_10_10_111,
        host:single-server-2_10_10_10_112,
        ;
 permit src = host:google-pub-dns-1_8_8_8_8,
              host:google-pub-dns-2_8_8_4_4,
              ;
        dst = user;
        prt = tcp 53,
              udp 53,
              ;
}
``` 

![image](https://github.com/orrence/Netspoc-Vue/assets/124901205/fc8978d6-2efc-439d-ba87-c7f8f5ef0e44)

**Comment by orrence** [comment]
Hallo lankenau-dp,
Policy-Web zeigt Netspoc-Daten an. Diese werden zu diesem Zweck vom Netspoc-Format in JSON "expandiert". Dabei werden die Gruppen aufgelöst und sind somit in den JSON-Daten gar nicht mehr vorhanden. Dies zu ändern würde bedeuten, das ganze Datenformat auf den Kopf zu stellen und daher stehen die Chancen sehr schlecht, dass wir diesen Wunsch erfüllen können.

Aber trotzdem Danke für das Feedback!
